### ISSUE TITLE
developer_id type not working

### ISSUE THREAD

**Issue by georges** [rubymotion-community/motion-provisioning#32]
with the following configuration

```
app.release do
    app.codesign_certificate = MotionProvisioning.certificate(platform: :mac, type: :developer_id, free: false)
end
```

```
bundle exec rake build:release
```

I get

```
      Info Do you want to add the 'provisioning' folder fo your '.gitignore' file? (Recommended) (Y/n): 
      Info Your Apple ID email: <REDACTED>
      Info Do you want to save the email to the config file ('/Users/gauberger/dev/islandmagic/obelisk-osx/provisioning/config.yaml') so you dont have to type it again? (Y/n): 
      Info Logging into the Developer Portal with email '<REDACTED>'.
Available session is not valid any more. Continuing with normal login.
      Info Selected team "< REDACTED >).
rake aborted!
NoMethodError: undefined method `developer_i_d_application' for Spaceship::Portal::Certificate:Class
/Users/gauberger/.rvm/gems/ruby-2.6.4@obelisk/gems/fastlane-2.158.0/spaceship/lib/spaceship/base.rb:191:in `method_missing'
/Users/gauberger/.rvm/gems/ruby-2.6.4@obelisk/bundler/gems/motion-provisioning-3baf8750c996/lib/motion-provisioning/certificate.rb:166:in `certificate_type'
/Users/gauberger/.rvm/gems/ruby-2.6.4@obelisk/bundler/gems/motion-provisioning-3baf8750c996/lib/motion-provisioning/certificate.rb:144:in `certificates'
/Users/gauberger/.rvm/gems/ruby-2.6.4@obelisk/bundler/gems/motion-provisioning-3baf8750c996/lib/motion-provisioning/certificate.rb:42:in `certificate_name'
/Users/gauberger/.rvm/gems/ruby-2.6.4@obelisk/bundler/gems/motion-provisioning-3baf8750c996/lib/motion-provisioning.rb:204:in `certificate'
/Users/gauberger/dev/islandmagic/obelisk-osx/Rakefile:60:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:207:in `release'
/Users/gauberger/dev/islandmagic/obelisk-osx/Rakefile:59:in `block in <top (required)>'
/Users/gauberger/.rvm/gems/ruby-2.6.4@obelisk/gems/bubble-wrap-1.9.7/lib/bubble-wrap/ext/motion_project_app.rb:10:in `block in setup_with_bubblewrap'
/Library/RubyMotion/lib/motion/project/config.rb:122:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:122:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:122:in `setup'
/Users/gauberger/.rvm/gems/ruby-2.6.4@obelisk/gems/sugarcube-4.0.0/lib/sugarcube_pre_setup.rb:37:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Users/gauberger/.rvm/gems/ruby-2.6.4@obelisk/gems/bubble-wrap-1.9.7/lib/bubble-wrap/ext/motion_project_app.rb:24:in `config_with_bubblewrap'
/Users/gauberger/.rvm/gems/ruby-2.6.4@obelisk/bundler/gems/motion.h-b78219e6d490/lib/motion.h.rb:23:in `build_with_motion_h'
/Users/gauberger/.rubymotion/rubymotion-templates/motion/project/template/osx.rb:50:in `block (2 levels) in <top (required)>'
/Users/gauberger/.rvm/gems/ruby-2.6.4@obelisk/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/gauberger/.rvm/rubies/ruby-2.6.4/bin/bundle:30:in `block in <main>'
/Users/gauberger/.rvm/rubies/ruby-2.6.4/bin/bundle:22:in `<main>'
Tasks: TOP => build:release
(See full trace by running task with --trace)
```

using `type: :distribution` works

**Comment by andrewhavens** [comment]
@georges Should be fixed now on master with this commit https://github.com/HipByte/motion-provisioning/commit/9aae12035aaf643501d6cca67e7bf71e7971f0d4
